### ISSUE TITLE
debounce/throttle implementation

### ISSUE THREAD

**Issue by bw1984** [jonathan-fielding/SimpleStateManager#41]
Im not sure how the current window resize observer is written but i did a quick search in the source for requestAnimationFrame and couldnt see anything.

For performance it may be worth swapping out the debounce function written by david walsh (http://davidwalsh.name/javascript-debounce-function) with something that utilises requestAnimationFrame as it is more efficient. I think there are functions out there which utilise a similar method for observing scroll position and they just fallback to setTimeout for older browsers. 

What do you think?

**Comment by jonathan-fielding** [comment]
I am currently rewriting, will take this into account as we currently use David Walsh's old debounce https://github.com/SimpleStateManager/SimpleStateManager/blob/master/src/ssm.js#L388

**Comment by jonathan-fielding** [comment]
I am rewriting to make the code easier to maintain and to be ES6 as you can deliver es6 bundles now to some browsers which also will help perf

**Comment by erolabzait** [comment]
Any timeframe for the new release?

**Comment by jonathan-fielding** [comment]
I want to make sure that I put enough testing into this release so I expect it to be a couple of weeks. Most of the refactor is done but I have to build the new website, write the new documentation etc

**Comment by jonathan-fielding** [comment]
https://github.com/SimpleStateManager/SimpleStateManager/pull/40 PR for the work here

**Comment by jonathan-fielding** [comment]
Released with this feature in 4.0.0
