### ISSUE TITLE
ssm.getCurrentState(s)

### ISSUE THREAD

**Issue by bw1984** [jonathan-fielding/SimpleStateManager#46]
would it be possible to add a method to fetch the current state at any given time? either as an object containing the details or just the id (so we can use it to then call ssm.getState(name);) 

this is loosely related to the other feature request i raised, but would be useful as a standalone method also

**Comment by jonathan-fielding** [comment]
Could this not be achieved by simply doing:

ssm.getStates().filter((state) => state.active);

**Comment by bw1984** [comment]
that looks simple enough! i'll give it a go. I didnt realise i had access to state.active

**Comment by jonathan-fielding** [comment]
Its JavaScript so most time you can get access to most things, I long for true private scoping in es6 classes (which i read is coming soon)
