### ISSUE TITLE
event object on initial load

### ISSUE THREAD

**Issue by bw1984** [jonathan-fielding/SimpleStateManager#49]
This issues relates to the recent update based on #45 

Your inclusion of an event object on state change works great when the state enter/leave is triggered by an event in the usual way, but on first page load (with the last argument set to true in the code below), e returns 'undefined'. It would be useful if it could detect the state on first load also. 

```
ssm.getState('min_large').attachCallback('enter', function(e)
{
	console.log(e);
}, true);
```

**Comment by jonathan-fielding** [comment]
Only just seen this, will have a look

**Comment by jonathan-fielding** [comment]
Ok so that was a bug so I have fixed it now and written a unit test to prevent regression @bw1984
